wandb_version: 1

_use_trajectory_view_api:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb_impala.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
after_train_step:
  desc: null
  value: null
broadcast_interval:
  desc: null
  value: 4
decay:
  desc: null
  value: 0.99
entropy_coeff:
  desc: null
  value: 0.01
entropy_coeff_end:
  desc: null
  value: 5.031298011165886e-05
entropy_coeff_schedule:
  desc: null
  value: null
entropy_coeff_start:
  desc: null
  value: 0.004507549936043152
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
epsilon:
  desc: null
  value: 0.1
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: 40.0
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1087
learner_queue_size:
  desc: null
  value: 25
learner_queue_timeout:
  desc: null
  value: 30
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.0005
lr_end:
  desc: null
  value: 5.315862338293029e-06
lr_schedule:
  desc: null
  value: null
lr_start:
  desc: null
  value: 0.0005380274933495606
max_sample_requests_in_flight_per_worker:
  desc: null
  value: 6
metrics_smoothing_episodes:
  desc: null
  value: 3000
min_iter_time_s:
  desc: null
  value: 10
minibatch_buffer_size:
  desc: null
  value: 6676
model:
  desc: null
  value:
    custom_model: fc_masked_model_v1
    fcnet_activation: relu
    fcnet_hiddens:
    - 1087
    - 1087
model_net:
  desc: null
  value: fc_masked_model_v1
momentum:
  desc: null
  value: 0.0
num_aggregation_workers:
  desc: null
  value: 0
num_data_loader_buffers:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 4
num_gpus:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 28
num_workers:
  desc: null
  value: 80
opt_type:
  desc: null
  value: adam
replay_buffer_num_slots:
  desc: null
  value: 67
replay_proportion:
  desc: null
  value: 0.09615575999127396
rollout_fragment_length:
  desc: null
  value: 726
seed:
  desc: null
  value: 0
train_batch_size:
  desc: null
  value: 89635
vf_loss_coeff:
  desc: null
  value: 0.8432633510952231
vtrace:
  desc: null
  value: true
vtrace_clip_pg_rho_threshold:
  desc: null
  value: 0.6419332725716996
vtrace_clip_rho_threshold:
  desc: null
  value: 0.6310843045846337
