wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: complete_episodes
clip_param:
  desc: null
  value: 0.3571016001590159
entropy_coeff:
  desc: null
  value: 0.00911585651381852
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.42066448460017614
kl_target:
  desc: null
  value: 0.47139161820092923
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1120
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.00030758962038225445
metrics_smoothing_episodes:
  desc: null
  value: 1000
model:
  desc: null
  value:
    custom_model: fc_masked_model_tf
    fcnet_activation: relu
    fcnet_hiddens:
    - 1120
    - 1120
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 24
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 1167
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 26952
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 32001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 17
vf_loss_coeff:
  desc: null
  value: 0.7250701815079215
vf_share_layers:
  desc: null
  value: false
