wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 6
entropy_coeff_end:
  value: 9.976701737688958e-05
entropy_coeff_start:
  value: 0.007707483427572599
layer_size:
  value: 845
learner_queue_size:
  value: 8
lr_end:
  value: 5.218591031163185e-05
lr_start:
  value: 0.000567873312680288
max_sample_requests_in_flight_per_worker:
  value: 7
minibatch_buffer_size:
  value: 15726
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 27
replay_buffer_num_slots:
  value: 35
replay_proportion:
  value: 0.17879672678715053
rollout_fragment_length:
  value: 791
train_batch_size:
  value: 73035
vf_loss_coeff:
  value: 0.9555249063736103
vtrace_clip_pg_rho_threshold:
  value: 0.9544995689987685
vtrace_clip_rho_threshold:
  value: 0.9138651604291862
