wandb_version: 1

activation_fn:
  value: relu
broadcast_interval:
  value: 7
entropy_coeff_end:
  value: 5.597355806155502e-07
entropy_coeff_start:
  value: 0.002439167513911962
layer_size:
  value: 943
learner_queue_size:
  value: 7
lr_end:
  value: 5.113717653024409e-05
lr_start:
  value: 0.0002701444380553825
max_sample_requests_in_flight_per_worker:
  value: 4
minibatch_buffer_size:
  value: 12924
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 14
replay_buffer_num_slots:
  value: 86
replay_proportion:
  value: 0.25521896979249714
rollout_fragment_length:
  value: 997
train_batch_size:
  value: 108215
vf_loss_coeff:
  value: 0.6924375065286281
vtrace_clip_pg_rho_threshold:
  value: 0.8853919929247653
vtrace_clip_rho_threshold:
  value: 0.6837112966128849
