wandb_version: 1

broadcast_interval:
  value: 8
entropy_coeff_end:
  value: 8.649555359476304e-05
entropy_coeff_start:
  value: 0.008636359769657
layer_size:
  value: 913
learner_queue_size:
  value: 22
lr_end:
  value: 9.029397673723725e-06
lr_start:
  value: 5.839849997309824e-05
max_sample_requests_in_flight_per_worker:
  value: 8
minibatch_buffer_size:
  value: 8163
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 7
num_sgd_iter:
  value: 29
replay_buffer_num_slots:
  value: 49
replay_proportion:
  value: 0.31718324809265375
rollout_fragment_length:
  value: 1127
train_batch_size:
  value: 103718
vf_loss_coeff:
  value: 0.5997134271729094
vtrace_clip_pg_rho_threshold:
  value: 0.9504362042812217
vtrace_clip_rho_threshold:
  value: 0.6540219016505091
