wandb_version: 1

broadcast_interval:
  value: 4
entropy_coeff_end:
  value: 5.031298011165886e-05
entropy_coeff_start:
  value: 0.004507549936043152
layer_size:
  value: 1087
learner_queue_size:
  value: 25
lr_end:
  value: 5.315862338293029e-06
lr_start:
  value: 0.0005380274933495606
max_sample_requests_in_flight_per_worker:
  value: 6
minibatch_buffer_size:
  value: 6676
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 4
num_sgd_iter:
  value: 28
replay_buffer_num_slots:
  value: 67
replay_proportion:
  value: 0.09615575999127396
rollout_fragment_length:
  value: 726
train_batch_size:
  value: 89635
vf_loss_coeff:
  value: 0.8432633510952231
vtrace_clip_pg_rho_threshold:
  value: 0.6419332725716996
vtrace_clip_rho_threshold:
  value: 0.6310843045846337
