wandb_version: 1

broadcast_interval:
  value: 1
entropy_coeff_end:
  value: 3.321431660069215e-05
entropy_coeff_start:
  value: 0.002583972919707721
layer_size:
  value: 869
learner_queue_size:
  value: 9
lr_end:
  value: 6.083774749774488e-06
lr_start:
  value: 0.0005663896897975664
max_sample_requests_in_flight_per_worker:
  value: 7
minibatch_buffer_size:
  value: 15895
num_envs_per_worker:
  value: 6
num_sgd_iter:
  value: 25
replay_buffer_num_slots:
  value: 52
replay_proportion:
  value: 0.441772736980922
rollout_fragment_length:
  value: 661
train_batch_size:
  value: 102283
vf_loss_coeff:
  value: 0.6403934740059332
vtrace_clip_pg_rho_threshold:
  value: 0.7884052858965532
vtrace_clip_rho_threshold:
  value: 0.5391681996081193
