wandb_version: 1

broadcast_interval:
  value: 7
entropy_coeff_end:
  value: 4.136121112278121e-05
entropy_coeff_start:
  value: 0.009199344468099686
layer_size:
  value: 1119
learner_queue_size:
  value: 16
lr_end:
  value: 8.141529391295917e-06
lr_start:
  value: 0.00014875426493358572
max_sample_requests_in_flight_per_worker:
  value: 3
minibatch_buffer_size:
  value: 8248
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 30
replay_buffer_num_slots:
  value: 73
replay_proportion:
  value: 0.4018795773522581
rollout_fragment_length:
  value: 591
train_batch_size:
  value: 19122
vf_loss_coeff:
  value: 0.6845010899655982
vtrace_clip_pg_rho_threshold:
  value: 0.750926058683579
vtrace_clip_rho_threshold:
  value: 0.549421934852351
