wandb_version: 1

broadcast_interval:
  value: 5
entropy_coeff_end:
  value: 7.463215693218322e-05
entropy_coeff_start:
  value: 0.006520994378121179
layer_size:
  value: 802
learner_queue_size:
  value: 6
lr_end:
  value: 9.733144049939787e-06
lr_start:
  value: 0.000803248244865875
max_sample_requests_in_flight_per_worker:
  value: 2
minibatch_buffer_size:
  value: 7655
num_envs_per_worker:
  value: 5
num_sgd_iter:
  value: 5
replay_buffer_num_slots:
  value: 52
replay_proportion:
  value: 0.31921660516551403
rollout_fragment_length:
  value: 1078
train_batch_size:
  value: 81891
vf_loss_coeff:
  value: 0.9204484463362963
vtrace_clip_pg_rho_threshold:
  value: 0.675153717463078
vtrace_clip_rho_threshold:
  value: 0.9929201560185545
