wandb_version: 1

broadcast_interval:
  value: 4
entropy_coeff_end:
  value: 8.627088645956375e-05
entropy_coeff_start:
  value: 0.002631157183822591
layer_size:
  value: 928
learner_queue_size:
  value: 21
lr_end:
  value: 6.832536857146039e-06
lr_start:
  value: 0.0009396265460626634
max_sample_requests_in_flight_per_worker:
  value: 8
minibatch_buffer_size:
  value: 9495
num_envs_per_worker:
  value: 4
num_sgd_iter:
  value: 12
replay_buffer_num_slots:
  value: 6
replay_proportion:
  value: 0.3562487350200527
rollout_fragment_length:
  value: 753
train_batch_size:
  value: 66435
vf_loss_coeff:
  value: 0.8748633050811756
vtrace_clip_pg_rho_threshold:
  value: 0.8069176419728692
vtrace_clip_rho_threshold:
  value: 0.6256996227953675
