wandb_version: 1

broadcast_interval:
  value: 3
entropy_coeff_end:
  value: 2.5857420551570998e-05
entropy_coeff_start:
  value: 0.0017558870853485132
layer_size:
  value: 1122
learner_queue_size:
  value: 17
lr_end:
  value: 2.744223311193012e-06
lr_start:
  value: 0.00030606798728519786
max_sample_requests_in_flight_per_worker:
  value: 4
minibatch_buffer_size:
  value: 15133
num_envs_per_worker:
  value: 5
num_sgd_iter:
  value: 30
replay_buffer_num_slots:
  value: 66
replay_proportion:
  value: 0.4018546352866268
rollout_fragment_length:
  value: 708
train_batch_size:
  value: 27294
vf_loss_coeff:
  value: 0.5028705983786208
vtrace_clip_pg_rho_threshold:
  value: 0.5363267012326709
vtrace_clip_rho_threshold:
  value: 0.7963931443547382
