wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    code_path: code/JSS/random_loop.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta55
