wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 2
entropy_coeff_end:
  value: 8.453275959960423e-05
entropy_coeff_start:
  value: 0.001213547385806556
layer_size:
  value: 1009
learner_queue_size:
  value: 32
lr_end:
  value: 9.352925235940566e-05
lr_start:
  value: 0.000831773891447129
max_sample_requests_in_flight_per_worker:
  value: 5
minibatch_buffer_size:
  value: 4099
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 8
num_sgd_iter:
  value: 14
replay_buffer_num_slots:
  value: 94
replay_proportion:
  value: 0.11320994927131328
rollout_fragment_length:
  value: 1023
train_batch_size:
  value: 84211
vf_loss_coeff:
  value: 0.8224673178534478
vtrace_clip_pg_rho_threshold:
  value: 0.903292723022357
vtrace_clip_rho_threshold:
  value: 0.5512498908630341
