wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.2985666870999333
entropy_coeff:
  value: 0.005012696697476095
kl_coeff:
  value: 0.4616389109668823
layer_size:
  value: 742
lr:
  value: 0.0002708999653190027
num_envs_per_worker:
  value: 8
num_sgd_iter:
  value: 24
rollout_fragment_length:
  value: 562
sgd_minibatch_size:
  value: 11464
vf_clip_param:
  value: 18
vf_loss_coeff:
  value: 0.5513292152438943
