wandb_version: 1

batch_mode:
  value: complete_episodes
clip_param:
  value: 0.39047092506444664
entropy_coeff:
  value: 0.0018784991214578987
kl_coeff:
  value: 0.583249318669985
layer_size:
  value: 980
lr:
  value: 5.0422808714326984e-05
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 20
rollout_fragment_length:
  value: 912
sgd_minibatch_size:
  value: 28368
vf_clip_param:
  value: 13
vf_loss_coeff:
  value: 0.5789525443648086
