wandb_version: 1

batch_mode:
  value: complete_episodes
clip_param:
  value: 0.3345680088392847
entropy_coeff:
  value: 0.0025033108374313898
kl_coeff:
  value: 0.5642042502538362
layer_size:
  value: 1036
lr:
  value: 0.0005008755818073248
num_envs_per_worker:
  value: 5
num_sgd_iter:
  value: 24
rollout_fragment_length:
  value: 556
sgd_minibatch_size:
  value: 29593
vf_clip_param:
  value: 15
vf_loss_coeff:
  value: 0.5663782579534258
