wandb_version: 1

batch_mode:
  value: complete_episodes
clip_param:
  value: 0.3844455312507513
entropy_coeff:
  value: 1.1900947634824814e-05
kl_coeff:
  value: 0.2053914885628815
layer_size:
  value: 704
lr:
  value: 0.0008974823208114456
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 27
rollout_fragment_length:
  value: 796
sgd_minibatch_size:
  value: 23361
vf_clip_param:
  value: 18
vf_loss_coeff:
  value: 0.7888461930210886
