wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.3936132404933365
entropy_coeff:
  value: 0.0019307607096909945
kl_coeff:
  value: 0.5428638776295676
layer_size:
  value: 821
lr:
  value: 0.000641186056185637
num_envs_per_worker:
  value: 7
num_sgd_iter:
  value: 37
rollout_fragment_length:
  value: 411
sgd_minibatch_size:
  value: 16273
vf_clip_param:
  value: 14
vf_loss_coeff:
  value: 0.5130705596608197
