wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 1
entropy_coeff_end:
  value: 3.3836258209205515e-05
entropy_coeff_start:
  value: 0.0015648167733714514
layer_size:
  value: 960
learner_queue_size:
  value: 16
lr_end:
  value: 5.9885811107052735e-06
lr_start:
  value: 0.000510129714472443
max_sample_requests_in_flight_per_worker:
  value: 6
minibatch_buffer_size:
  value: 12552
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 18
replay_buffer_num_slots:
  value: 77
replay_proportion:
  value: 0.4177409862010193
rollout_fragment_length:
  value: 975
train_batch_size:
  value: 17800
vf_loss_coeff:
  value: 0.9626358502004227
vtrace_clip_pg_rho_threshold:
  value: 0.8451551965891413
vtrace_clip_rho_threshold:
  value: 0.8731038404065605
