wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 4
entropy_coeff_end:
  value: 6.303440259716269e-05
entropy_coeff_start:
  value: 0.005652192130477259
layer_size:
  value: 810
learner_queue_size:
  value: 20
lr_end:
  value: 3.3993080472219407e-06
lr_start:
  value: 1.898894570254751e-05
max_sample_requests_in_flight_per_worker:
  value: 8
minibatch_buffer_size:
  value: 7193
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 8
num_sgd_iter:
  value: 7
replay_buffer_num_slots:
  value: 63
replay_proportion:
  value: 0.2796380900800012
rollout_fragment_length:
  value: 938
train_batch_size:
  value: 106729
vf_loss_coeff:
  value: 0.8392742887152667
vtrace_clip_pg_rho_threshold:
  value: 0.7479873690345974
vtrace_clip_rho_threshold:
  value: 0.6469097275024047
