wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    code_path: code/JSS/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
batch_mode:
  desc: null
  value: truncate_episodes
clip_param:
  desc: null
  value: 0.3
entropy_coeff:
  desc: null
  value: 0.0001
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: torch
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.2
kl_target:
  desc: null
  value: 0.01
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1024
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 5.0e-05
lr_schedule:
  desc: null
  value: null
metrics_smoothing_episodes:
  desc: null
  value: 100000
model:
  desc: null
  value:
    custom_model: fc_masked_model
    fcnet_activation: relu
    fcnet_hiddens:
    - 1024
    - 1024
num_envs_per_worker:
  desc: null
  value: 2
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 30
num_workers:
  desc: null
  value: 79
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 1024
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 13384
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 161792
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 10.0
vf_loss_coeff:
  desc: null
  value: 1.0
vf_share_layers:
  desc: null
  value: false
