wandb_version: 1

batch_mode:
  value: complete_episodes
clip_param:
  value: 0.2624939725754559
entropy_coeff:
  value: 0.004922324694102254
kl_coeff:
  value: 0.5685797445544722
layer_size:
  value: 755
lr:
  value: 0.0034413572602004366
num_envs_per_worker:
  value: 1
num_sgd_iter:
  value: 31
rollout_fragment_length:
  value: 467
sgd_minibatch_size:
  value: 22257
vf_clip_param:
  value: 11
vf_loss_coeff:
  value: 0.7795284259159367
