wandb_version: 1

broadcast_interval:
  value: 4
entropy_coeff_end:
  value: 2.5306874355578314e-05
entropy_coeff_start:
  value: 0.00379575315959961
layer_size:
  value: 871
learner_queue_size:
  value: 7
lr_end:
  value: 3.3300920924336243e-06
lr_start:
  value: 0.00045002380062325354
max_sample_requests_in_flight_per_worker:
  value: 1
minibatch_buffer_size:
  value: 10948
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 21
replay_buffer_num_slots:
  value: 74
replay_proportion:
  value: 0.11784090802232194
rollout_fragment_length:
  value: 697
train_batch_size:
  value: 43629
vf_loss_coeff:
  value: 0.5530316367397752
vtrace_clip_pg_rho_threshold:
  value: 0.7468591403604301
vtrace_clip_rho_threshold:
  value: 0.8455402361409221
