wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 6
entropy_coeff_end:
  value: 4.4962383322718735e-05
entropy_coeff_start:
  value: 0.0010161120678766988
layer_size:
  value: 1101
learner_queue_size:
  value: 23
lr_end:
  value: 6.355740398600608e-06
lr_start:
  value: 0.0006357327952498009
max_sample_requests_in_flight_per_worker:
  value: 4
minibatch_buffer_size:
  value: 15832
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 7
num_sgd_iter:
  value: 15
replay_buffer_num_slots:
  value: 49
replay_proportion:
  value: 0.3632849589914687
rollout_fragment_length:
  value: 789
train_batch_size:
  value: 52218
vf_loss_coeff:
  value: 0.740100262582442
vtrace_clip_pg_rho_threshold:
  value: 0.9136897232109512
vtrace_clip_rho_threshold:
  value: 0.8389485791470892
