wandb_version: 1

activation_fn:
  value: relu
broadcast_interval:
  value: 4
entropy_coeff_end:
  value: 7.370080309973999e-05
entropy_coeff_start:
  value: 0.00496514318143988
layer_size:
  value: 1054
learner_queue_size:
  value: 30
lr_end:
  value: 5.719639787331055e-06
lr_start:
  value: 0.0007472619476121901
max_sample_requests_in_flight_per_worker:
  value: 5
minibatch_buffer_size:
  value: 7428
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 7
num_sgd_iter:
  value: 17
replay_buffer_num_slots:
  value: 36
replay_proportion:
  value: 0.4280374403351325
rollout_fragment_length:
  value: 869
train_batch_size:
  value: 37457
vf_loss_coeff:
  value: 0.6069149425401448
vtrace_clip_pg_rho_threshold:
  value: 0.9697817589513251
vtrace_clip_rho_threshold:
  value: 0.7437680522887922
