wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_mode:
  desc: null
  value: truncate_episodes
clip_param:
  desc: null
  value: 0.4888340333172321
entropy_coeff:
  desc: null
  value: 0.006512033190880834
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /home/jovyan/pierre/JSS/JSS/env/instances/ta41
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /home/jovyan/pierre/JSS/JSS/env/instances/ta41
kl_coeff:
  desc: null
  value: 0.2393789351621287
kl_target:
  desc: null
  value: 0.16162668478617392
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 435
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.000479
lr_end:
  desc: null
  value: 7.611722000162562e-05
lr_start:
  desc: null
  value: 0.0008122561042033457
metrics_smoothing_episodes:
  desc: null
  value: 2000
model:
  desc: null
  value:
    custom_model: fc_masked_model_tf
    fcnet_activation: relu
    fcnet_hiddens:
    - 435
    - 435
    vf_share_layers: false
num_envs_per_worker:
  desc: null
  value: 4
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 10
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 769
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 33000
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 225280
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 15
vf_loss_coeff:
  desc: null
  value: 0.6503633243314274
vf_share_layers:
  desc: null
  value: false
