wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_use_trajectory_view_api:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.4
    code_path: code/JSS/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: truncate_episodes
clip_actions:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.3
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: 180
compress_observations:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
eager_tracing:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.0
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /home/jovyan/JSS/JSS/env/instances/ta51
evaluation_config:
  desc: null
  value: {}
evaluation_interval:
  desc: null
  value: null
evaluation_num_episodes:
  desc: null
  value: 10
evaluation_num_workers:
  desc: null
  value: 0
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: null
horizon:
  desc: null
  value: null
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_evaluation:
  desc: null
  value:
  - is
  - wis
kl_coeff:
  desc: null
  value: 0.3
kl_target:
  desc: null
  value: 0.01
lambda:
  desc: null
  value: 1.0
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0005
lr_schedule:
  desc: null
  value: null
memory:
  desc: null
  value: 0
memory_per_worker:
  desc: null
  value: 0
metrics_smoothing_episodes:
  desc: null
  value: 100000
min_iter_time_s:
  desc: null
  value: 0
model:
  desc: null
  value:
    custom_model: fc_masked_model
    fcnet_activation: relu
    fcnet_hiddens:
    - 512
    - 512
monitor:
  desc: null
  value: false
multiagent:
  desc: null
  value:
    observation_fn: null
    policies: {}
    policies_to_train: null
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
no_eager_on_workers:
  desc: null
  value: false
normalize_actions:
  desc: null
  value: false
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 30
num_workers:
  desc: null
  value: 7
object_store_memory:
  desc: null
  value: 0
object_store_memory_per_worker:
  desc: null
  value: 0
observation_filter:
  desc: null
  value: NoFilter
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
replay_sequence_length:
  desc: null
  value: 1
rollout_fragment_length:
  desc: null
  value: 200
sample_async:
  desc: null
  value: false
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 128
shuffle_buffer_size:
  desc: null
  value: 0
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
soft_horizon:
  desc: null
  value: false
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: 0
train_batch_size:
  desc: null
  value: 4000
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 10.0
vf_loss_coeff:
  desc: null
  value: 1.0
vf_share_layers:
  desc: null
  value: false
