wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_mode:
  desc: null
  value: truncate_episodes
clip_param:
  desc: null
  value: 0.49926284632417106
entropy_coeff:
  desc: null
  value: 0.00098571529578211
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /home/jovyan/pierre/JSS/JSS/env/instances/ta41
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /home/jovyan/pierre/JSS/JSS/env/instances/ta41
kl_coeff:
  desc: null
  value: 0.26230715221906087
kl_target:
  desc: null
  value: 0.10315450894946347
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 466
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.000479
lr_end:
  desc: null
  value: 3.135686370518696e-05
lr_start:
  desc: null
  value: 0.000936029469983379
metrics_smoothing_episodes:
  desc: null
  value: 2000
model:
  desc: null
  value:
    custom_model: fc_masked_model_tf
    fcnet_activation: relu
    fcnet_hiddens:
    - 466
    - 466
    vf_share_layers: false
num_envs_per_worker:
  desc: null
  value: 4
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 14
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 795
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 33000
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 225280
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 22
vf_loss_coeff:
  desc: null
  value: 0.9643748475005733
vf_share_layers:
  desc: null
  value: false
