wandb_version: 1

broadcast_interval:
  value: 3
entropy_coeff_end:
  value: 6.226008206077311e-05
entropy_coeff_start:
  value: 0.0057372833770423124
layer_size:
  value: 888
learner_queue_size:
  value: 8
lr_end:
  value: 4.0808387763571015e-06
lr_start:
  value: 0.0004726903965086013
max_sample_requests_in_flight_per_worker:
  value: 8
minibatch_buffer_size:
  value: 12655
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 9
replay_buffer_num_slots:
  value: 17
replay_proportion:
  value: 0.4052398027298947
rollout_fragment_length:
  value: 527
train_batch_size:
  value: 84567
vf_loss_coeff:
  value: 0.8080281875105622
vtrace_clip_pg_rho_threshold:
  value: 0.7283573370973473
vtrace_clip_rho_threshold:
  value: 0.9838485761035476
