wandb_version: 1

broadcast_interval:
  value: 6
entropy_coeff_end:
  value: 5.065379864407306e-05
entropy_coeff_start:
  value: 0.006070679562194826
layer_size:
  value: 1180
learner_queue_size:
  value: 5
lr_end:
  value: 5.281406190888809e-06
lr_start:
  value: 0.00027113781511680767
max_sample_requests_in_flight_per_worker:
  value: 8
minibatch_buffer_size:
  value: 15247
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 21
replay_buffer_num_slots:
  value: 24
replay_proportion:
  value: 0.04017003443546874
rollout_fragment_length:
  value: 869
train_batch_size:
  value: 95039
vf_loss_coeff:
  value: 0.818183842292268
vtrace_clip_pg_rho_threshold:
  value: 0.818145012986162
vtrace_clip_rho_threshold:
  value: 0.4594934108212426
