wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_use_trajectory_view_api:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.8
batch_mode:
  desc: null
  value: complete_episodes
clip_actions:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.2638618813663309
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: 180
compress_observations:
  desc: null
  value: false
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
date:
  desc: null
  value: 2020-11-20_04-11-34
eager_tracing:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.000759388365477132
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /home/jovyan/pierre/JSS/JSS/env/instances/ta51
evaluation_config:
  desc: null
  value: {}
evaluation_interval:
  desc: null
  value: null
evaluation_num_episodes:
  desc: null
  value: 10
evaluation_num_workers:
  desc: null
  value: 0
experiment_id:
  desc: null
  value: f7405768ba0e4dd4b563a407ca1af3f3
experiment_tag:
  desc: null
  value: 20__fake_gpus=False,_use_trajectory_view_api=False,batch_mode=complete_episodes,callbacks=<class
    'JSS.CustomCallbacks.CustomCallbacks'>,clip_actions=True,clip_param=0.26386,clip_rewards=None,collect_metrics_timeout=180,compress_observations=False,create_env_on_driver=False,custom_eval_function=None,eager_tracing=False,entropy_coeff=0.00075939,instance_path=_home_jovyan_pierre_JSS_JSS_env_instances_ta51,evaluation_interval=None,evaluation_num_episodes=10,evaluation_num_workers=0,type=StochasticSampling,explore=True,fake_sampler=False,framework=torch,gamma=1.0,grad_clip=None,horizon=None,ignore_worker_failures=False,in_evaluation=False,input=sampler,input_evaluation=('is',
    'wis'),kl_coeff=0.29209,kl_target=0.24494,lambda=0.97962,inter_op_parallelism_threads=8,intra_op_parallelism_threads=8,log_level=WARN,log_sys_usage=True,api_key=3487a01956bf67cc7882bca2a38f70c8c95f8463,project=JSS_WANDB_PPO,lr=0.00013841,memory=0,memory_per_worker=0,metrics_smoothing_episodes=1000,min_iter_time_s=0,_time_major=False,conv_activation=relu,conv_filters=None,custom_action_dist=None,custom_model=fc_masked_model,custom_preprocessor=None,dim=84,fcnet_activation=tanh,fcnet_hiddens=(1024,
    1024),framestack=True,free_log_std=False,grayscale=False,lstm_cell_size=256,lstm_use_prev_action_reward=False,max_seq_len=20,no_final_linear=False,use_lstm=False,vf_share_layers=True,zero_mean=True,monitor=False,observation_fn=None,policies_to_train=None,policy_mapping_fn=None,replay_mode=independent,no_done_at_end=False,normalize_actions=False,num_cpus_for_driver=1,num_cpus_per_worker=1,num_envs_per_worker=7,num_gpus=1,num_gpus_per_worker=0,num_sgd_iter=25,num_workers=11,object_store_memory=0,object_store_memory_per_worker=0,observation_filter=NoFilter,output=None,output_compress_columns=('obs',
    'new_obs'),output_max_file_size=67108864,postprocess_inputs=False,preprocessor_pref=deepmind,remote_env_batch_wait_ms=0,remote_worker_envs=False,replay_sequence_length=1,rollout_fragment_length=1024,sample_async=False,seed=0,sgd_minibatch_size=8192,shuffle_buffer_size=0,shuffle_sequences=True,simple_optimizer=False,soft_horizon=False,synchronize_filters=True,allow_soft_placement=True,CPU=1,allow_growth=True,inter_op_parallelism_threads=2,intra_op_parallelism_threads=2,log_device_placement=False,timesteps_per_iteration=0,train_batch_size=78848,use_critic=True,use_gae=True,vf_clip_param=6.2489,vf_loss_coeff=0.55765,vf_share_layers=False
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
horizon:
  desc: null
  value: null
hostname:
  desc: null
  value: 3015b0f6dbfa
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_evaluation:
  desc: null
  value:
  - is
  - wis
kl_coeff:
  desc: null
  value: 0.2920913003918847
kl_target:
  desc: null
  value: 0.24494499021200755
lambda:
  desc: null
  value: 0.9796153652885037
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
logger_config:
  desc: null
  value:
    wandb:
      api_key: 3487a01956bf67cc7882bca2a38f70c8c95f8463
      project: JSS_WANDB_PPO
lr:
  desc: null
  value: 0.0001384070400904588
lr_schedule:
  desc: null
  value: null
memory:
  desc: null
  value: 0
memory_per_worker:
  desc: null
  value: 0
metrics_smoothing_episodes:
  desc: null
  value: 1000
min_iter_time_s:
  desc: null
  value: 0
model:
  desc: null
  value:
    _time_major: false
    conv_activation: relu
    conv_filters: null
    custom_action_dist: null
    custom_model: fc_masked_model
    custom_model_config: {}
    custom_preprocessor: null
    dim: 84
    fcnet_activation: tanh
    fcnet_hiddens:
    - 1024
    - 1024
    framestack: true
    free_log_std: false
    grayscale: false
    lstm_cell_size: 256
    lstm_use_prev_action_reward: false
    max_seq_len: 20
    no_final_linear: false
    use_lstm: false
    vf_share_layers: true
    zero_mean: true
monitor:
  desc: null
  value: false
multiagent:
  desc: null
  value:
    observation_fn: null
    policies: {}
    policies_to_train: null
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
node_ip:
  desc: null
  value: 172.17.0.3
normalize_actions:
  desc: null
  value: false
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 7
num_gpus:
  desc: null
  value: 1
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 25
num_workers:
  desc: null
  value: 11
object_store_memory:
  desc: null
  value: 0
object_store_memory_per_worker:
  desc: null
  value: 0
observation_filter:
  desc: null
  value: NoFilter
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
pid:
  desc: null
  value: 14860
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
replay_sequence_length:
  desc: null
  value: 1
rollout_fragment_length:
  desc: null
  value: 1024
sample_async:
  desc: null
  value: false
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 8192
shuffle_buffer_size:
  desc: null
  value: 0
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: true
soft_horizon:
  desc: null
  value: false
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: 0
train_batch_size:
  desc: null
  value: 78848
trial_id:
  desc: null
  value: ac6a3756
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 6.24890057604105
vf_loss_coeff:
  desc: null
  value: 0.5576464860549492
vf_share_layers:
  desc: null
  value: false
