wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
activation_fn:
  desc: null
  value: tanh
batch_mode:
  desc: null
  value: complete_episodes
clip_param:
  desc: null
  value: 0.2914284270193051
entropy_coeff_end:
  desc: null
  value: 8.052384193371975e-05
entropy_coeff_start:
  desc: null
  value: 0.008718981150951216
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.22966237887809648
kl_target:
  desc: null
  value: 0.3954380526808351
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1227
log_level:
  desc: null
  value: WARN
lr_end:
  desc: null
  value: 4.148014524462449e-06
lr_start:
  desc: null
  value: 0.0009442599695664345
metrics_smoothing_episodes:
  desc: null
  value: 1000
model:
  desc: null
  value:
    custom_model: fc_masked_model_v1
    fcnet_activation: relu
    fcnet_hiddens:
    - 1227
    - 1227
model_net:
  desc: null
  value: fc_masked_model_v1
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 25
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 535
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 10346
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 16001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 17
vf_loss_coeff:
  desc: null
  value: 0.5867687258795142
vf_share_layers:
  desc: null
  value: false
