wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 4
entropy_coeff_end:
  value: 4.572883971232337e-05
entropy_coeff_start:
  value: 0.004325714946198849
layer_size:
  value: 941
learner_queue_size:
  value: 5
lr_end:
  value: 4.7943705623369656e-05
lr_start:
  value: 7.694825631170576e-05
max_sample_requests_in_flight_per_worker:
  value: 6
minibatch_buffer_size:
  value: 6066
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 1
num_sgd_iter:
  value: 22
replay_buffer_num_slots:
  value: 13
replay_proportion:
  value: 0.07399685845973741
rollout_fragment_length:
  value: 539
train_batch_size:
  value: 72490
vf_loss_coeff:
  value: 0.8709126320104975
vtrace_clip_pg_rho_threshold:
  value: 0.548568390192572
vtrace_clip_rho_threshold:
  value: 0.7808112567647403
