wandb_version: 1

batch_mode:
  value: complete_episodes
clip_param:
  value: 0.23857499694901993
entropy_coeff:
  value: 0.004559701814161942
kl_coeff:
  value: 0.3586136716758296
layer_size:
  value: 657
lr:
  value: 0.002796721804481175
num_envs_per_worker:
  value: 8
num_sgd_iter:
  value: 32
rollout_fragment_length:
  value: 587
sgd_minibatch_size:
  value: 15082
vf_clip_param:
  value: 19
vf_loss_coeff:
  value: 0.6837934660715984
