wandb_version: 1

_use_trajectory_view_api:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb_impala.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
activation_fn:
  desc: null
  value: relu
after_train_step:
  desc: null
  value: null
batch_mode:
  desc: null
  value: truncate_episodes
broadcast_interval:
  desc: null
  value: 5
clip_actions:
  desc: null
  value: true
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: 180
compress_observations:
  desc: null
  value: false
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
date:
  desc: null
  value: 2020-11-29_21-48-53
decay:
  desc: null
  value: 0.99
eager_tracing:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.005051250773883176
entropy_coeff_end:
  desc: null
  value: 5.413946261648715e-05
entropy_coeff_schedule:
  desc: null
  value:
  - - 0
    - 0.005051250773883176
  - - 10000000
    - 5.413946261648715e-05
entropy_coeff_start:
  desc: null
  value: 0.005051250773883176
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
epsilon:
  desc: null
  value: 0.1
evaluation_config:
  desc: null
  value: {}
evaluation_interval:
  desc: null
  value: null
evaluation_num_episodes:
  desc: null
  value: 10
evaluation_num_workers:
  desc: null
  value: 0
experiment_id:
  desc: null
  value: 618b9cf7ffb841939068f4c31e654ac7
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: 40.0
horizon:
  desc: null
  value: null
hostname:
  desc: null
  value: 775a13addddf
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_evaluation:
  desc: null
  value:
  - is
  - wis
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1203
learner_queue_size:
  desc: null
  value: 14
learner_queue_timeout:
  desc: null
  value: 30
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
logger_config:
  desc: null
  value: null
lr:
  desc: null
  value: 0.000514522678462503
lr_end:
  desc: null
  value: 8.590801998845022e-05
lr_schedule:
  desc: null
  value:
  - - 0
    - 0.000514522678462503
  - - 10000000
    - 8.590801998845022e-05
lr_start:
  desc: null
  value: 0.000514522678462503
max_sample_requests_in_flight_per_worker:
  desc: null
  value: 1
memory:
  desc: null
  value: 0
memory_per_worker:
  desc: null
  value: 0
metrics_smoothing_episodes:
  desc: null
  value: 1000
min_iter_time_s:
  desc: null
  value: 0
minibatch_buffer_size:
  desc: null
  value: 5018
model:
  desc: null
  value:
    _time_major: false
    conv_activation: relu
    conv_filters: null
    custom_action_dist: null
    custom_model: fc_masked_model_v2
    custom_model_config: {}
    custom_preprocessor: null
    dim: 84
    fcnet_activation: relu
    fcnet_hiddens:
    - 1203
    - 1203
    framestack: true
    free_log_std: false
    grayscale: false
    lstm_cell_size: 256
    lstm_use_prev_action_reward: false
    max_seq_len: 20
    no_final_linear: false
    use_lstm: false
    vf_share_layers: true
    zero_mean: true
model_net:
  desc: null
  value: fc_masked_model_v2
momentum:
  desc: null
  value: 0.0
monitor:
  desc: null
  value: false
multiagent:
  desc: null
  value:
    observation_fn: null
    policies: {}
    policies_to_train: null
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
node_ip:
  desc: null
  value: 172.17.0.16
normalize_actions:
  desc: null
  value: false
num_aggregation_workers:
  desc: null
  value: 0
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_data_loader_buffers:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 0
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 8
num_workers:
  desc: null
  value: 80
object_store_memory:
  desc: null
  value: 0
object_store_memory_per_worker:
  desc: null
  value: 0
observation_filter:
  desc: null
  value: NoFilter
opt_type:
  desc: null
  value: adam
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
pid:
  desc: null
  value: 24702
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
replay_buffer_num_slots:
  desc: null
  value: 64
replay_proportion:
  desc: null
  value: 0.1557828296197067
replay_sequence_length:
  desc: null
  value: 1
rollout_fragment_length:
  desc: null
  value: 839
sample_async:
  desc: null
  value: false
seed:
  desc: null
  value: 0
shuffle_buffer_size:
  desc: null
  value: 0
soft_horizon:
  desc: null
  value: false
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: 0
train_batch_size:
  desc: null
  value: 78741
vf_loss_coeff:
  desc: null
  value: 0.8752254282733144
vtrace:
  desc: null
  value: true
vtrace_clip_pg_rho_threshold:
  desc: null
  value: 0.6914134909295423
vtrace_clip_rho_threshold:
  desc: null
  value: 0.7970482209325378
