wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
activation_fn:
  desc: null
  value: tanh
batch_mode:
  desc: null
  value: complete_episodes
clip_param:
  desc: null
  value: 0.37423621789759964
entropy_coeff_end:
  desc: null
  value: 5.0964603484867434e-05
entropy_coeff_start:
  desc: null
  value: 0.008807632117629761
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.5714387900872377
kl_target:
  desc: null
  value: 0.12336017296422291
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1040
log_level:
  desc: null
  value: WARN
lr_end:
  desc: null
  value: 1.2770285638821194e-06
lr_start:
  desc: null
  value: 2.537692960414632e-05
metrics_smoothing_episodes:
  desc: null
  value: 1000
model:
  desc: null
  value:
    custom_model: fc_masked_model_v1
    fcnet_activation: relu
    fcnet_hiddens:
    - 1040
    - 1040
model_net:
  desc: null
  value: fc_masked_model_v1
num_envs_per_worker:
  desc: null
  value: 5
num_gpus:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 23
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 762
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 14396
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 16001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 15
vf_loss_coeff:
  desc: null
  value: 0.8997882301202265
vf_share_layers:
  desc: null
  value: false
