wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: truncate_episodes
clip_param:
  desc: null
  value: 0.36465618773264924
entropy_coeff:
  desc: null
  value: 0.0022906295906927033
env:
  desc: null
  value: jss_env
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.31352219887511634
kl_target:
  desc: null
  value: 0.3893927539193154
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 851
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.0009612389552998161
metrics_smoothing_episodes:
  desc: null
  value: 1000
num_envs_per_worker:
  desc: null
  value: 2
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 23
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 347
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 23597
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 32001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 11
vf_loss_coeff:
  desc: null
  value: 0.7906459700393291
vf_share_layers:
  desc: null
  value: false
