wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: truncate_episodes
clip_param:
  desc: null
  value: 0.24929519816550627
entropy_coeff:
  desc: null
  value: 0.004400609255314343
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.36821818571384657
kl_target:
  desc: null
  value: 0.1786543209981876
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1239
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.0008707032096209506
metrics_smoothing_episodes:
  desc: null
  value: 1000
model:
  desc: null
  value:
    custom_model: fc_masked_model_v1
    fcnet_activation: relu
    fcnet_hiddens:
    - 1239
    - 1239
num_envs_per_worker:
  desc: null
  value: 6
num_gpus:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 30
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 1148
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 5254
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 16001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 19
vf_loss_coeff:
  desc: null
  value: 0.9192834176684832
vf_share_layers:
  desc: null
  value: false
