wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 6
entropy_coeff_end:
  value: 2.824634642016133e-06
entropy_coeff_start:
  value: 0.009846436074108492
layer_size:
  value: 838
learner_queue_size:
  value: 26
lr_end:
  value: 2.6585999612191043e-05
lr_start:
  value: 0.0006677239477262202
max_sample_requests_in_flight_per_worker:
  value: 5
minibatch_buffer_size:
  value: 5588
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 21
replay_buffer_num_slots:
  value: 65
replay_proportion:
  value: 0.04068033230854645
rollout_fragment_length:
  value: 560
train_batch_size:
  value: 49666
vf_loss_coeff:
  value: 0.8967813976379748
vtrace_clip_pg_rho_threshold:
  value: 0.67022649956742
vtrace_clip_rho_threshold:
  value: 0.8921197007401793
