wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.2926966120586501
entropy_coeff:
  value: 0.0001733255771049968
kl_coeff:
  value: 0.48507577692936843
layer_size:
  value: 554
lr:
  value: 0.0003344173206093793
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 36
rollout_fragment_length:
  value: 476
sgd_minibatch_size:
  value: 19020
vf_clip_param:
  value: 16
vf_loss_coeff:
  value: 0.8173860722481145
