wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 2
entropy_coeff_end:
  value: 7.444009844203677e-05
entropy_coeff_start:
  value: 0.0061032655991702205
layer_size:
  value: 1197
learner_queue_size:
  value: 5
lr_end:
  value: 9.634682175445284e-05
lr_start:
  value: 0.0006493453060503644
max_sample_requests_in_flight_per_worker:
  value: 5
minibatch_buffer_size:
  value: 9272
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 8
num_sgd_iter:
  value: 16
replay_buffer_num_slots:
  value: 93
replay_proportion:
  value: 0.028487487154121416
rollout_fragment_length:
  value: 701
train_batch_size:
  value: 102466
vf_loss_coeff:
  value: 0.6107431088475694
vtrace_clip_pg_rho_threshold:
  value: 0.6262198461742079
vtrace_clip_rho_threshold:
  value: 0.5816441777494559
