wandb_version: 1

activation_fn:
  value: relu
broadcast_interval:
  value: 5
entropy_coeff_end:
  value: 5.413946261648715e-05
entropy_coeff_start:
  value: 0.005051250773883176
layer_size:
  value: 1203
learner_queue_size:
  value: 14
lr_end:
  value: 8.590801998845022e-05
lr_start:
  value: 0.000514522678462503
max_sample_requests_in_flight_per_worker:
  value: 1
minibatch_buffer_size:
  value: 5018
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 1
num_sgd_iter:
  value: 8
replay_buffer_num_slots:
  value: 64
replay_proportion:
  value: 0.1557828296197067
rollout_fragment_length:
  value: 839
train_batch_size:
  value: 78741
vf_loss_coeff:
  value: 0.8752254282733144
vtrace_clip_pg_rho_threshold:
  value: 0.6914134909295423
vtrace_clip_rho_threshold:
  value: 0.7970482209325378
