wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_use_trajectory_view_api:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: truncate_episodes
clip_actions:
  desc: null
  value: true
clip_param:
  desc: null
  value: 0.2926966120586501
clip_rewards:
  desc: null
  value: null
collect_metrics_timeout:
  desc: null
  value: 180
compress_observations:
  desc: null
  value: false
create_env_on_driver:
  desc: null
  value: false
custom_eval_function:
  desc: null
  value: null
custom_resources_per_worker:
  desc: null
  value: {}
date:
  desc: null
  value: 2020-12-01_11-10-42
eager_tracing:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.0001733255771049968
entropy_coeff_schedule:
  desc: null
  value: null
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta41
evaluation_config:
  desc: null
  value: {}
evaluation_interval:
  desc: null
  value: null
evaluation_num_episodes:
  desc: null
  value: 10
evaluation_num_workers:
  desc: null
  value: 0
experiment_id:
  desc: null
  value: 2838b34efbbb4f09869178045cd8ab79
exploration_config:
  desc: null
  value:
    type: StochasticSampling
explore:
  desc: null
  value: true
extra_python_environs_for_driver:
  desc: null
  value: {}
extra_python_environs_for_worker:
  desc: null
  value: {}
fake_sampler:
  desc: null
  value: false
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
horizon:
  desc: null
  value: null
hostname:
  desc: null
  value: 5ba8e70479cc
ignore_worker_failures:
  desc: null
  value: false
in_evaluation:
  desc: null
  value: false
input:
  desc: null
  value: sampler
input_evaluation:
  desc: null
  value:
  - is
  - wis
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta41
kl_coeff:
  desc: null
  value: 0.48507577692936843
kl_target:
  desc: null
  value: 0.2
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 554
local_tf_session_args:
  desc: null
  value:
    inter_op_parallelism_threads: 8
    intra_op_parallelism_threads: 8
log_level:
  desc: null
  value: WARN
log_sys_usage:
  desc: null
  value: true
logger_config:
  desc: null
  value: null
lr:
  desc: null
  value: 0.0003344173206093793
lr_schedule:
  desc: null
  value: null
memory:
  desc: null
  value: 0
memory_per_worker:
  desc: null
  value: 0
metrics_smoothing_episodes:
  desc: null
  value: 1000
min_iter_time_s:
  desc: null
  value: 0
model:
  desc: null
  value:
    _time_major: false
    conv_activation: relu
    conv_filters: null
    custom_action_dist: null
    custom_model: fc_masked_model_tf
    custom_model_config: {}
    custom_preprocessor: null
    dim: 84
    fcnet_activation: relu
    fcnet_hiddens:
    - 554
    - 554
    framestack: true
    free_log_std: false
    grayscale: false
    lstm_cell_size: 256
    lstm_use_prev_action_reward: false
    max_seq_len: 20
    no_final_linear: false
    use_lstm: false
    vf_share_layers: false
    zero_mean: true
monitor:
  desc: null
  value: false
multiagent:
  desc: null
  value:
    observation_fn: null
    policies: {}
    policies_to_train: null
    policy_mapping_fn: null
    replay_mode: independent
no_done_at_end:
  desc: null
  value: false
node_ip:
  desc: null
  value: 172.17.0.16
normalize_actions:
  desc: null
  value: false
num_cpus_for_driver:
  desc: null
  value: 1
num_cpus_per_worker:
  desc: null
  value: 1
num_envs_per_worker:
  desc: null
  value: 3
num_gpus:
  desc: null
  value: 1
num_gpus_per_worker:
  desc: null
  value: 0
num_sgd_iter:
  desc: null
  value: 36
num_workers:
  desc: null
  value: 80
object_store_memory:
  desc: null
  value: 0
object_store_memory_per_worker:
  desc: null
  value: 0
observation_filter:
  desc: null
  value: NoFilter
optimizer:
  desc: null
  value: {}
output:
  desc: null
  value: null
output_compress_columns:
  desc: null
  value:
  - obs
  - new_obs
output_max_file_size:
  desc: null
  value: 67108864
pid:
  desc: null
  value: 32248
postprocess_inputs:
  desc: null
  value: false
preprocessor_pref:
  desc: null
  value: deepmind
remote_env_batch_wait_ms:
  desc: null
  value: 0
remote_worker_envs:
  desc: null
  value: false
replay_sequence_length:
  desc: null
  value: 1
rollout_fragment_length:
  desc: null
  value: 476
sample_async:
  desc: null
  value: false
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 19020
shuffle_buffer_size:
  desc: null
  value: 0
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
soft_horizon:
  desc: null
  value: false
synchronize_filters:
  desc: null
  value: true
tf_session_args:
  desc: null
  value:
    allow_soft_placement: true
    device_count:
      CPU: 1
    gpu_options:
      allow_growth: true
    inter_op_parallelism_threads: 2
    intra_op_parallelism_threads: 2
    log_device_placement: false
timesteps_per_iteration:
  desc: null
  value: 0
train_batch_size:
  desc: null
  value: 32000
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 16
vf_loss_coeff:
  desc: null
  value: 0.8173860722481145
vf_share_layers:
  desc: null
  value: false
