wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.3052829509658238
entropy_coeff:
  value: 0.009617727286826472
kl_coeff:
  value: 0.4202426581890283
layer_size:
  value: 733
lr:
  value: 0.0005610344052954213
num_envs_per_worker:
  value: 4
num_sgd_iter:
  value: 25
rollout_fragment_length:
  value: 443
sgd_minibatch_size:
  value: 24415
vf_clip_param:
  value: 11
vf_loss_coeff:
  value: 0.8134448672902497
