wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.2605950814876122
entropy_coeff:
  value: 0.009004998259275303
kl_coeff:
  value: 0.4119000317616881
layer_size:
  value: 758
lr:
  value: 0.0004738063886185659
num_envs_per_worker:
  value: 7
num_sgd_iter:
  value: 37
rollout_fragment_length:
  value: 643
sgd_minibatch_size:
  value: 27992
vf_clip_param:
  value: 16
vf_loss_coeff:
  value: 0.8499065951546672
