wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.33406643547968173
entropy_coeff:
  value: 0.0015251067678013364
kl_coeff:
  value: 0.37997744144460355
layer_size:
  value: 604
lr:
  value: 1.9056553360219153e-05
num_envs_per_worker:
  value: 4
num_sgd_iter:
  value: 34
rollout_fragment_length:
  value: 398
sgd_minibatch_size:
  value: 4259
vf_clip_param:
  value: 17
vf_loss_coeff:
  value: 0.506997884843878
