wandb_version: 1

batch_mode:
  value: truncate_episodes
clip_param:
  value: 0.3564382266254361
entropy_coeff:
  value: 0.00424586493735538
kl_coeff:
  value: 0.2929888606288054
layer_size:
  value: 555
lr:
  value: 0.0007747446296469098
num_envs_per_worker:
  value: 4
num_sgd_iter:
  value: 30
rollout_fragment_length:
  value: 480
sgd_minibatch_size:
  value: 10057
vf_clip_param:
  value: 14
vf_loss_coeff:
  value: 0.9169262007424237
