wandb_version: 1

activation_fn:
  value: tanh
broadcast_interval:
  value: 1
entropy_coeff_end:
  value: 6.932648900735115e-05
entropy_coeff_start:
  value: 0.009104010035289713
layer_size:
  value: 914
learner_queue_size:
  value: 8
lr_end:
  value: 7.082186906977046e-05
lr_start:
  value: 8.194190132893118e-05
max_sample_requests_in_flight_per_worker:
  value: 1
minibatch_buffer_size:
  value: 7777
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 15
replay_buffer_num_slots:
  value: 76
replay_proportion:
  value: 0.0821277315396608
rollout_fragment_length:
  value: 750
train_batch_size:
  value: 68603
vf_loss_coeff:
  value: 0.5971027493321173
vtrace_clip_pg_rho_threshold:
  value: 0.5754561316090296
vtrace_clip_rho_threshold:
  value: 0.9652259088697839
