wandb_version: 1

broadcast_interval:
  value: 2
entropy_coeff_end:
  value: 1.6509007235566076e-05
entropy_coeff_start:
  value: 0.005972862116003233
layer_size:
  value: 934
learner_queue_size:
  value: 7
lr_end:
  value: 7.247778975886541e-06
lr_start:
  value: 0.0007837946152111741
max_sample_requests_in_flight_per_worker:
  value: 7
minibatch_buffer_size:
  value: 9692
num_envs_per_worker:
  value: 3
num_sgd_iter:
  value: 23
replay_buffer_num_slots:
  value: 23
replay_proportion:
  value: 0.4586407420237665
rollout_fragment_length:
  value: 696
train_batch_size:
  value: 119623
vf_loss_coeff:
  value: 0.5440702933802276
vtrace_clip_pg_rho_threshold:
  value: 0.8425770108826796
vtrace_clip_rho_threshold:
  value: 0.5197376291577132
