wandb_version: 1

broadcast_interval:
  value: 7
entropy_coeff_end:
  value: 9.099316873002894e-06
entropy_coeff_start:
  value: 0.009812966444785905
layer_size:
  value: 825
learner_queue_size:
  value: 10
lr_end:
  value: 5.475546990940949e-06
lr_start:
  value: 0.0006129773484754167
max_sample_requests_in_flight_per_worker:
  value: 3
minibatch_buffer_size:
  value: 7014
num_envs_per_worker:
  value: 1
num_sgd_iter:
  value: 6
replay_buffer_num_slots:
  value: 8
replay_proportion:
  value: 0.4435985868130052
rollout_fragment_length:
  value: 673
train_batch_size:
  value: 117911
vf_loss_coeff:
  value: 0.6894714284708086
vtrace_clip_pg_rho_threshold:
  value: 0.6720361197381801
vtrace_clip_rho_threshold:
  value: 0.5850325320640893
