wandb_version: 1

broadcast_interval:
  value: 3
entropy_coeff_end:
  value: 7.587026420366213e-05
entropy_coeff_start:
  value: 0.0023658155534115434
layer_size:
  value: 1025
learner_queue_size:
  value: 12
lr_end:
  value: 3.336460917919917e-06
lr_start:
  value: 0.0003911370751947371
max_sample_requests_in_flight_per_worker:
  value: 8
minibatch_buffer_size:
  value: 14749
num_envs_per_worker:
  value: 1
num_sgd_iter:
  value: 10
replay_buffer_num_slots:
  value: 24
replay_proportion:
  value: 0.26760977297040334
rollout_fragment_length:
  value: 919
train_batch_size:
  value: 110749
vf_loss_coeff:
  value: 0.5548389564302982
vtrace_clip_pg_rho_threshold:
  value: 0.5501162679039547
vtrace_clip_rho_threshold:
  value: 0.6923888196328032
