wandb_version: 1

broadcast_interval:
  value: 7
entropy_coeff_end:
  value: 9.821734991410428e-05
entropy_coeff_start:
  value: 0.00529670328312516
layer_size:
  value: 1167
learner_queue_size:
  value: 11
lr_end:
  value: 1.8010944871817021e-06
lr_start:
  value: 0.0006117905789077824
max_sample_requests_in_flight_per_worker:
  value: 7
minibatch_buffer_size:
  value: 8406
num_envs_per_worker:
  value: 2
num_sgd_iter:
  value: 15
replay_buffer_num_slots:
  value: 18
replay_proportion:
  value: 0.03431962113307885
rollout_fragment_length:
  value: 583
train_batch_size:
  value: 116867
vf_loss_coeff:
  value: 0.9416162600133958
vtrace_clip_pg_rho_threshold:
  value: 0.9535953736348948
vtrace_clip_rho_threshold:
  value: 0.5955554132613883
