wandb_version: 1

broadcast_interval:
  value: 1
entropy_coeff_end:
  value: 3.303730286634008e-05
entropy_coeff_start:
  value: 0.0025960936351051003
layer_size:
  value: 886
learner_queue_size:
  value: 15
lr_end:
  value: 7.972788891242885e-06
lr_start:
  value: 0.00010992969873447563
max_sample_requests_in_flight_per_worker:
  value: 6
minibatch_buffer_size:
  value: 8670
num_envs_per_worker:
  value: 1
num_sgd_iter:
  value: 10
replay_buffer_num_slots:
  value: 12
replay_proportion:
  value: 0.4528835863074226
rollout_fragment_length:
  value: 728
train_batch_size:
  value: 26316
vf_loss_coeff:
  value: 0.9620941770745686
vtrace_clip_pg_rho_threshold:
  value: 0.6622020350183402
vtrace_clip_rho_threshold:
  value: 0.473570000082126
