wandb_version: 1

broadcast_interval:
  value: 8
entropy_coeff_end:
  value: 1.9407110939827043e-05
entropy_coeff_start:
  value: 0.005349336765045339
layer_size:
  value: 1033
learner_queue_size:
  value: 12
lr_end:
  value: 2.0613606732762507e-06
lr_start:
  value: 0.000809844140004025
max_sample_requests_in_flight_per_worker:
  value: 5
minibatch_buffer_size:
  value: 6901
num_envs_per_worker:
  value: 6
num_sgd_iter:
  value: 7
replay_buffer_num_slots:
  value: 1
replay_proportion:
  value: 0.14834414263137707
rollout_fragment_length:
  value: 1035
train_batch_size:
  value: 38852
vf_loss_coeff:
  value: 0.7166605656071696
vtrace_clip_pg_rho_threshold:
  value: 0.6070815123636361
vtrace_clip_rho_threshold:
  value: 0.33880286640904417
