wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: truncate_episodes
clip_param:
  desc: null
  value: 0.20537277204963206
entropy_coeff:
  desc: null
  value: 0.007801219872850608
env:
  desc: null
  value: jss_env
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: torch
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.36219838749569006
kl_target:
  desc: null
  value: 0.33737382677478217
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 855
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.0001736101625308174
metrics_smoothing_episodes:
  desc: null
  value: 1000
num_envs_per_worker:
  desc: null
  value: 1
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 24
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 791
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 23081
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 32001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 18
vf_loss_coeff:
  desc: null
  value: 0.5391444873840993
vf_share_layers:
  desc: null
  value: false
