wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: complete_episodes
clip_param:
  desc: null
  value: 0.2058685926754615
entropy_coeff:
  desc: null
  value: 0.009805417164301252
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.5800073447646986
kl_target:
  desc: null
  value: 0.22579718390116477
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 775
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.00019223195872792738
metrics_smoothing_episodes:
  desc: null
  value: 1000
model:
  desc: null
  value:
    custom_model: fc_masked_model_tf
    fcnet_activation: relu
    fcnet_hiddens:
    - 775
    - 775
num_envs_per_worker:
  desc: null
  value: 3
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 21
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 471
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 4642
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 32001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 11
vf_loss_coeff:
  desc: null
  value: 0.6807316023284837
vf_share_layers:
  desc: null
  value: false
