wandb_version: 1

_fake_gpus:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.10.11
    code_path: code/JSS/train_wandb.py
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_mode:
  desc: null
  value: complete_episodes
clip_param:
  desc: null
  value: 0.2992514929225657
entropy_coeff:
  desc: null
  value: 0.002641245205638827
env:
  desc: null
  value: jss_env
env_config:
  desc: null
  value:
    instance_path: /JSS/JSS/env/instances/ta51
evaluation_interval:
  desc: null
  value: null
framework:
  desc: null
  value: tf
gamma:
  desc: null
  value: 1.0
grad_clip:
  desc: null
  value: null
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
kl_coeff:
  desc: null
  value: 0.2157012564533147
kl_target:
  desc: null
  value: 0.15307485327876874
lambda:
  desc: null
  value: 1.0
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1030
log_level:
  desc: null
  value: WARN
lr:
  desc: null
  value: 0.0004044697344577501
metrics_smoothing_episodes:
  desc: null
  value: 1000
model:
  desc: null
  value:
    custom_model: fc_masked_model_tf
    fcnet_activation: relu
    fcnet_hiddens:
    - 1030
    - 1030
num_envs_per_worker:
  desc: null
  value: 2
num_gpus:
  desc: null
  value: 1
num_sgd_iter:
  desc: null
  value: 26
num_workers:
  desc: null
  value: 80
observation_filter:
  desc: null
  value: NoFilter
rollout_fragment_length:
  desc: null
  value: 773
seed:
  desc: null
  value: 0
sgd_minibatch_size:
  desc: null
  value: 31661
shuffle_sequences:
  desc: null
  value: true
simple_optimizer:
  desc: null
  value: false
train_batch_size:
  desc: null
  value: 32001
use_critic:
  desc: null
  value: true
use_gae:
  desc: null
  value: true
vf_clip_param:
  desc: null
  value: 20
vf_loss_coeff:
  desc: null
  value: 0.9301076260332083
vf_share_layers:
  desc: null
  value: false
