wandb_version: 1

activation_fn:
  value: relu
broadcast_interval:
  value: 5
entropy_coeff_end:
  value: 4.658018292837001e-05
entropy_coeff_start:
  value: 0.007816036963428278
layer_size:
  value: 922
learner_queue_size:
  value: 22
lr_end:
  value: 6.443221977226095e-05
lr_start:
  value: 0.0006448983044638122
max_sample_requests_in_flight_per_worker:
  value: 3
minibatch_buffer_size:
  value: 11358
model_net:
  value: fc_masked_model_v1
num_envs_per_worker:
  value: 6
num_sgd_iter:
  value: 15
replay_buffer_num_slots:
  value: 95
replay_proportion:
  value: 0.21647818966730642
rollout_fragment_length:
  value: 640
train_batch_size:
  value: 23006
vf_loss_coeff:
  value: 0.565625501810854
vtrace_clip_pg_rho_threshold:
  value: 0.5453147734984714
vtrace_clip_rho_threshold:
  value: 0.872353109004684
