wandb_version: 1

activation_fn:
  value: relu
broadcast_interval:
  value: 7
entropy_coeff_end:
  value: 7.854746097967058e-05
entropy_coeff_start:
  value: 0.0013421418071542157
layer_size:
  value: 1214
learner_queue_size:
  value: 27
lr_end:
  value: 6.047275960006391e-06
lr_start:
  value: 0.0009171351043741926
max_sample_requests_in_flight_per_worker:
  value: 1
minibatch_buffer_size:
  value: 13314
model_net:
  value: fc_masked_model_v2
num_envs_per_worker:
  value: 8
num_sgd_iter:
  value: 25
replay_buffer_num_slots:
  value: 100
replay_proportion:
  value: 0.0019650483078362813
rollout_fragment_length:
  value: 967
train_batch_size:
  value: 30555
vf_loss_coeff:
  value: 0.8023238999444668
vtrace_clip_pg_rho_threshold:
  value: 0.7829457820774688
vtrace_clip_rho_threshold:
  value: 0.8700751443879521
