wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.5
    code_path: code/JSS/RandomGreedy.py
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
activation:
  desc: null
  value: tanh
actors_per_cpu:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 64
env_name:
  desc: null
  value: job-shop-v0
epsilon:
  desc: null
  value: 0.9
epsilon_decay:
  desc: null
  value: 0.995
gamma:
  desc: null
  value: 0.999
instance:
  desc: null
  value: env/instances/ta51
instance_path:
  desc: null
  value: /JSS/JSS/env/instances/ta51
layer_nb:
  desc: null
  value: 2
layer_size:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 0.0005
max_steps_per_episode:
  desc: null
  value: 1000
minimal_epsilon:
  desc: null
  value: 0.1
nb_steps:
  desc: null
  value: 16
replay_buffer_size:
  desc: null
  value: 100000
running_sec_time:
  desc: null
  value: 900
seed:
  desc: null
  value: 0
tau:
  desc: null
  value: 0.001
update_network_step:
  desc: null
  value: 5
